#!/bin/bash -ex


dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}
VERSION="2.2.0"
URL="http://downloads.sourceforge.net/project/mibew/core/${VERSION}/mibew-${VERSION}.zip"

dl $URL /usr/local/src
