#!/bin/sh -ex

DB_NAME=mibew
DB_USER=mibew
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/mibew

# unpack and set permissions
mkdir -p $WEBROOT
unzip $SRC/mibew*.zip -d $WEBROOT
rm $SRC/mibew*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/images/avatar

# configure apache
a2dissite default
a2ensite mibew
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# preseed configuration
CONF=$WEBROOT/libs/config.php
sed -i "s|webimroot.*|webimroot = \"\";|" $CONF
sed -i "s|mysqldb.*|mysqldb = \"$DB_NAME\";|" $CONF
sed -i "s|mysqllogin.*|mysqllogin = \"$DB_USER\";|" $CONF
sed -i "s|mysqlpass.*|mysqlpass = \"$DB_PASS\";|" $CONF

# curl based install
URL="http://127.0.0.1/install"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}/index.php"
$CURL "${URL}/dbperform.php?act=ct"
$CURL "${URL}/index.php"

rm -f /tmp/cookie
rm -rf $WEBROOT/install

# set default password
MD5_PASS=$(echo -n $ADMIN_PASS | md5sum | cut -d " " -f 1)
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE chatoperator SET vcpassword=\"$MD5_PASS\" WHERE vclogin=\"$ADMIN_NAME\";"

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

