#!/bin/bash -e
# regenerate mibew mysql password

. /etc/default/inithooks

CONF=/var/www/mibew/configs/config.yml

PASSWORD=$(mcookie)
#sed -i "s|mysqlpass.*|mysqlpass = \"$PASSWORD\";|" $CONF
sed -i "0,/pass: \".*/s//pass: \"$DB_PASS\"/" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=mibew --pass="$PASSWORD"

