#!/bin/bash -e
# regenerate mibew mysql password

. /etc/default/inithooks

CONF=/var/www/mibew/libs/config.php

PASSWORD=$(mcookie)
sed -i "s|mysqlpass.*|mysqlpass = \"$PASSWORD\";|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=mibew --pass="$PASSWORD"

